### ISSUE TITLE
ion icons

### ISSUE THREAD

**Issue by fkaris** [ksurendra/ionic-framework-website-starter#1]
Hello thank you for the hard work, how do i make the ion icons work? they are not loading.

![image](https://user-images.githubusercontent.com/53820798/79569109-b4e16280-80bf-11ea-8135-28004173936d.png)

**Comment by thesurenk** [comment]
Thanks. You may use it like this.

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">    
    <!-- <script type='text/javascript' src="core/dist/ionic.js"></script> -->
    <link rel="stylesheet" href="https://unpkg.com/@ionic/core@5.0.0/css/ionic.bundle.css">
    <!-- <link rel="stylesheet" href="core/css/ionic.bundle.css"> -->
  </head>
  <body>
    <h1>Basic IonicFrameowork Usage Example</h1>
    <p>
    <br>
    <ion-title>This is <b>ion-title</b> Component</ion-title>
    <br> 
    This is <b>ion-icon</b> (Close) <ion-icon name="close"></ion-icon> Component. 
    <br>
    This is <b>ion-button</b> with <b>ion-icon</b> Component.
      <ion-button>
        <ion-icon name="close"></ion-icon> Clear
      </ion-button>
    </p>
      <script src="https://unpkg.com/@ionic/core@5.0.0/dist/ionic.js"></script>
      <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
  </body>
</html>
```

**Comment by fkaris** [comment]
there is no way to bring the icons locally?? like thejs

**Comment by fkaris** [comment]
> Thanks. You may use it like this.
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
>   <head>
>     <meta charset="utf-8">    
>     
>     <link rel="stylesheet" href="https://unpkg.com/@ionic/core@5.0.0/css/ionic.bundle.css">
>     
>   </head>
>   <body>
>     <h1>Basic IonicFrameowork Usage Example</h1>
>     <p>
>     <br>
>     <ion-title>This is <b>ion-title</b> Component</ion-title>
>     <br> 
>     This is <b>ion-icon</b> (Close) <ion-icon name="close"></ion-icon> Component. 
>     <br>
>     This is <b>ion-button</b> with <b>ion-icon</b> Component.
>       <ion-button>
>         <ion-icon name="close"></ion-icon> Clear
>       </ion-button>
>     </p>
>       <script src="https://unpkg.com/@ionic/core@5.0.0/dist/ionic.js"></script>
>       <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
>   </body>
> </html>
> ```


Hello Ksurendra, the use of this was to bring the ionic files locally not to use the links. is there a way you can keep it local like the files in the repo to add the icons?

**Comment by thesurenk** [comment]
There is an alternative way. If you see the 2nd part of README.md, i documented the process.
Also updated the codebase to use local instead of CDN. 

Breifly:
- Run `npm i`, then coy the `@ionic` folder from `node_modules` into your project
- Test the `.html` running on some web server 

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">    
    <link rel="stylesheet" href="core/css/ionic.bundle.css">
  </head>
  <body>
    <h1>Basic Ionic Framework (v5.0.0) Usage Example</h1>
    <p>
    <br>
    <ion-title>This is <b>ion-title</b> Component</ion-title>
    <br> 
    This is <b>ion-icon</b> (Close) <ion-icon name="close"></ion-icon> Component. 
    <br>
    This is <b>ion-button</b> with <b>ion-icon</b> Component.
      <ion-button>
        <ion-icon name="close"></ion-icon> Clear
      </ion-button>
    </p>

    <script type="module" src="core/dist/ionic/ionic.js"></script>
    <script nomodule src="core/dist/ionic/ionic.esm.js"></script>
  </body>
</html>
```

**Comment by fkaris** [comment]
``
Thank you for you
i did ::: npm install @ionic/core@5.0.*

so it  gave me the file structure with the ionicons there but still not working


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">    
    <link rel="stylesheet" href="core/css/ionic.bundle.css">
  </head>
  <body>
    <h1>Basic Ionic Framework (v5.0.0) Usage Example</h1>
    <p>
    <br>
    <ion-title>This is <b>ion-title</b> Component</ion-title>
    <br> 
    This is <b>ion-icon</b> (Close) <ion-icon name="close"></ion-icon> Component. 
    <br>
    This is <b>ion-button</b> with <b>ion-icon</b> Component.
      <ion-button>
        <ion-icon name="close"></ion-icon> Clear
      </ion-button>
    </p>

    <script type="module" src="core/dist/ionic/ionic.js"></script>
    <script nomodule src="core/dist/ionic/ionic.esm.js"></script>
    <script src="node_modules/ionicons/dist/ionicons.js"></script>
   

  </body>
</html>



![image](https://user-images.githubusercontent.com/53820798/79598960-6d71cb00-80ed-11ea-9ed7-c78142ff5ae6.png)



![image](https://user-images.githubusercontent.com/53820798/79598800-37344b80-80ed-11ea-8ce2-e5ff5aa8c7de.png)

**Comment by thesurenk** [comment]
You don't need to and should nto include anything from `node_modules`

Remove this line `<script src="node_modules/ionicons/dist/ionicons.js"></script>` 

`ionic` build includes `ionicons`.

Did you try to do a `git pull` from `master` branch and tried to run it ?

**Comment by fkaris** [comment]
i have tried to run the master branch same result. i have also remove the line still not working the ionicons , have you tested on your end and its working?

**Comment by thesurenk** [comment]
Yes.. all loading from my local 

<img width="1463" alt="Screen Shot 2020-04-18 at 6 31 59 PM" src="https://user-images.githubusercontent.com/902972/79673842-f139bf00-81a2-11ea-9a44-ad118154699b.png">

**Comment by fkaris** [comment]
do you mind sharing the code your using and files thank you.

**Comment by thesurenk** [comment]
the master branch in this repo
